// Generated by https://quicktype.io

export interface PropertyDetailedRent {
	property_id:          string;
	listing_id:           string;
	prop_type:            string;
	list_date:            string;
	last_update:          string;
	listing_status:       string;
	beds:                 number;
	description:          string;
	building:             Building;
	building_href:        string;
	branding:             Branding;
	baths_full:           number;
	prop_status:          string;
	year_built?:           number;
	address:              Address;
	features:             Feature[];
	client_display_flags: ClientDisplayFlags;
	listing_provider_url: ListingProviderURL;
	products:             string[];
	office:               Office;
	lead_forms:           LeadForms;
	lot_size:             Size;
	building_size:        Size;
	price:                number;
	rdc_web_url:          string;
	rdc_app_url:          string;
	baths:                number;
	mortgage:             Mortgage;
	data_source_name:     string;
	source:               string;
	detail_tracking:      string;
	lease_terms:          string;
	photo_count:          number;
	photos:               Photo[];
	schools:              School[];
}

export interface Address {
	city:                   string;
	country:                string;
	county:                 string;
	county_needed_for_uniq: boolean;
	lat:                    number;
	line:                   string;
	postal_code:            string;
	state_code:             string;
	state:                  string;
	time_zone:              string;
	neighborhood_name:      string;
	neighborhoods:          Neighborhood[];
	lon:                    number;
}

export interface Neighborhood {
	id:    string;
	level: string;
	name:  string;
}

export interface Branding {
	state_license: null;
}

export interface Building {
	id:        number;
	permalink: string;
}

export interface Size {
	size:  number;
	units: string;
}

export interface ClientDisplayFlags {
	presentation_status:            string;
	is_showcase:                    boolean;
	lead_form_phone_required:       boolean;
	price_change:                   number;
	has_specials:                   boolean;
	is_mls_rental:                  boolean;
	is_rental_community:            boolean;
	is_rental_unit:                 boolean;
	is_co_star:                     boolean;
	is_apartmentlist:               boolean;
	suppress_map_pin:               boolean;
	suppress_phone_call_lead_event: boolean;
	price_reduced:                  boolean;
	allows_cats:                    boolean;
	allows_dogs:                    boolean;
	allows_dogs_small:              boolean;
	allows_dogs_large:              boolean;
}

export interface Feature {
	category:        string;
	text:            string[];
	parent_category: string;
}

export interface LeadForms {
	form:            Form;
	show_agent:      boolean;
	show_broker:     boolean;
	show_provider:   boolean;
	show_management: boolean;
}

export interface Form {
	name:         Email;
	email:        Email;
	move_in_date: MoveInDate;
	phone:        FormPhone;
	message:      Email;
	show:         boolean;
}

export interface Email {
	required:                boolean;
	minimum_character_count: number;
}

export interface MoveInDate {
	required:                boolean;
	default_date:            string;
	minimum_days_from_today: number;
	maximum_days_from_today: number;
}

export interface FormPhone {
	required:                boolean;
	minimum_character_count: number;
	maximum_character_count: number;
}

export interface ListingProviderURL {
	level: string;
	type:  string;
	url:   string;
}

export interface Mortgage {
	rates_url: string;
}

export interface Office {
	id:     string;
	name:   string;
	email:  string;
	phones: PhoneElement[];
}

export interface PhoneElement {
	number:  string;
	type:    string;
	primary: boolean;
}

export interface Photo {
	href: string;
}

export interface School {
	nces_id:                string;
	id:                     string;
	greatschools_id:        string;
	name:                   string;
	education_levels:       EducationLevel[];
	funding_type:           string;
	lat:                    number;
	lon:                    number;
	student_count?:         number;
	student_teacher_ratio?: number;
	location:               Location;
	phone:                  string;
	distance_in_miles:      number;
	grades:                 Grades;
	relevance:              string;
	ratings:                Ratings;
}

export enum EducationLevel {
	Elementary = "elementary",
	High = "high",
	Middle = "middle",
}

export interface Grades {
	range: Range;
}

export interface Range {
	low:  string;
	high: string;
}

export interface Location {
	city_slug_id: string;
	postal_code:  string;
	state:        string;
	county:       string;
	city:         string;
	street:       string;
}

export interface Ratings {
	great_schools_rating: number | null;
	parent_rating:        number | null;
}
