// Generated by https://quicktype.io

export interface MortgageStats {
	loan_amount:                number;
	rate:                       number;
	term:                       number;
	monthly_payment:            number;
	principal_and_interest:     number;
	monthly_property_taxes:     number;
	monthly_home_insurance:     number;
	hoa_fees:                   number;
	monthly_mortgage_insurance: number;
	total_payment:              number;
	down_payment:               number;
}


export interface MortgageParams {
	hoi: string, // montly home insurance
    tax_rate: string, // property tax rate
    downpayment: string,
    price: string,
    term: string, // duration years
	rate: string, // interest rate
    apply_veterans_benefits?: boolean
}
