// Generated by https://quicktype.io

export interface PropertyDetailedBuy {
	property_id:          string;
	prop_status:          string;
	listing_id:           string;
	prop_type:            string;
	move_in_date:         null;
	list_date:            string;
	last_update:          string;
	broker:               Broker;
	year_built:           number;
	listing_status:       string;
	beds:                 number;
	description:          string;
	baths_full:           number;
	baths_half:           number;
	stories:              number;
	schools:              School[];
	heating:              null;
	cooling:              null;
	feature_tags:         string[];
	branding:             Branding;
	address:              PropertyDetailedBuyAddress;
	features:             Feature[];
	mls:                  Mls;
	client_display_flags: ClientDisplayFlags;
	tax_history:          TaxHistory[];
	sold_history:         SoldHistory[];
	property_history:     PropertyHistory[];
	public_records:       PublicRecord[];
	products:             string[];
	office:               Office;
	agents:               Agent[];
	lead_forms:           LeadForms;
	building_size:        BuildingSize;
	price:                number;
	rdc_web_url:          string;
	rdc_app_url:          string;
	baths:                number;
	photo_count:          number;
	raw:                  Raw;
	photo_attribution:    string[];
	mortgage:             Mortgage;
	data_source_name:     string;
	detail_tracking:      string;
	photos:               PhotoElement[];
}

export interface PropertyDetailedBuyAddress {
	city:                    string;
	line:                    string;
	postal_code:             string;
	address_validation_code: string;
	state_code:              string;
	state:                   string;
	county:                  string;
	fips_code:               string;
	county_needed_for_uniq:  boolean;
	time_zone:               string;
	lat:                     number;
	lon:                     number;
	neighborhood_name:       string;
	neighborhoods:           Neighborhood[];
}

export interface Neighborhood {
	name:       string;
	city:       string;
	state_code: string;
	level:      string;
	id:         null | string;
}

export interface Agent {
	name:             string;
	profile_name:     string;
	advertiser_id:    string;
	href:             null;
	photo:            null;
	nrds_id:          null;
	nrds_verified_id: null;
	office_name:      string;
	email:            string;
	slogan:           null;
	state_license:    null;
	mls_memberships:  MlsMemberships;
	id:               string;
	primary:          boolean;
}

export interface MlsMemberships {
	member: MlsMembershipsMember;
}

export interface MlsMembershipsMember {
	agent_system_id:  string;
	name:             string;
	office_system_id: string;
	id:               string;
	abbreviation:     string;
}

export interface Branding {
	listing_agent:  Listing;
	listing_office: Listing;
	team_name:      null;
}

export interface Listing {
	photo_attribution: Details;
	details:           Details;
}

export interface Details {
	name:              string;
	photo:             null | string;
	phone:             null | string;
	slogan:            null;
	show_realtor_logo: boolean;
	link:              null | string;
	accent_color:      null;
	state_license?:    null;
}

export interface Broker {
	advertiser_id: number;
	name:          string;
	phone1:        Phone1;
}

export interface Phone1 {
	number: string;
	type:   string;
}

export interface BuildingSize {
	size:  number;
	units: string;
}

export interface ClientDisplayFlags {
	presentation_status:                string;
	is_showcase:                        boolean;
	lead_form_phone_required:           boolean;
	price_change:                       number;
	is_co_broke_email:                  boolean;
	has_open_house:                     boolean;
	is_foreclosure:                     boolean;
	is_short_sale:                      boolean;
	is_co_broke_phone:                  boolean;
	is_new_listing:                     boolean;
	is_new_plan:                        boolean;
	is_new_construction:                boolean;
	is_turbo:                           boolean;
	is_office_standard_listing:         boolean;
	suppress_map_pin:                   boolean;
	show_contact_a_lender_in_lead_form: boolean;
	show_veterans_united_in_lead_form:  boolean;
	flip_the_market_enabled:            boolean;
	is_showcase_choice_enabled:         boolean;
}

export interface Feature {
	category:        string;
	parent_category: string;
	text:            string[];
}

export interface LeadForms {
	form:                    Form;
	show_agent:              boolean;
	show_broker:             boolean;
	show_builder:            boolean;
	show_contact_a_lender:   boolean;
	show_veterans_united:    boolean;
	form_type:               string;
	lead_type:               string;
	is_lcm_enabled:          boolean;
	flip_the_market_enabled: boolean;
	local_phone:             string;
	local_phones:            LocalPhones;
	show_text_leads:         boolean;
	cashback_enabled:        boolean;
	smarthome_enabled:       boolean;
}

export interface Form {
	name:    Email;
	email:   Email;
	phone:   FormPhone;
	message: Email;
	show:    boolean;
}

export interface Email {
	required:                boolean;
	minimum_character_count: number;
}

export interface FormPhone {
	required:                boolean;
	minimum_character_count: number;
	maximum_character_count: number;
}

export interface LocalPhones {
	comm_console_mweb: string;
}

export interface Mls {
	name:         string;
	id:           string;
	plan_id:      null;
	abbreviation: string;
	type:         string;
}

export interface Mortgage {
	rates_url: string;
	estimate:  Estimate;
}

export interface Estimate {
	loan_amount:                number;
	rate:                       number;
	term:                       number;
	monthly_payment:            number;
	principal_and_interest:     number;
	monthly_property_taxes:     number;
	monthly_home_insurance:     number;
	hoa_fees:                   number;
	monthly_mortgage_insurance: number;
	total_payment:              number;
	down_payment:               number;
}

export interface Office {
	name:            string;
	advertiser_id:   number;
	mls_set:         string;
	href:            string;
	photo:           OfficePhoto;
	email:           string;
	slogan:          string;
	phones:          PhoneElement[];
	address:         OfficeAddress;
	advantage_phone: AdvantagePhone;
	mls_membership:  MlsMembership;
	id:              string;
}

export interface OfficeAddress {
	city:       string;
	state_code: string;
}

export interface AdvantagePhone {
	display_number: string;
}

export interface MlsMembership {
	member: MlsMembershipMember;
}

export interface MlsMembershipMember {
	office_system_id: string;
}

export interface PhoneElement {
	number:   string;
	type:     string;
	primary?: boolean;
}

export interface OfficePhoto {
	href: string;
}

export interface PhotoElement {
	description: string;
	href:        string;
	tags:        Tag[];
	type:        Type;
}

export interface Tag {
	label:       string;
	probability: number;
}

export enum Type {
	RealtordotcomMlsListingImage = "realtordotcom_mls_listing_image",
}

export interface PropertyHistory {
	event_name:      string;
	date:            string;
	price:           number;
	price_range_min: null;
	price_range_max: null;
	price_changed:   number;
	sqft:            number;
	datasource_name: string;
	source:          string;
}

export interface PublicRecord {
	baths:          null;
	baths_1qtr:     null;
	baths_3qtr:     null;
	baths_full:     null;
	baths_half:     null;
	beds:           null;
	construction:   null;
	cooling:        null;
	cl_id:          string;
	date_updated:   string;
	distinct_baths: null;
	exterior1:      null;
	exterior2:      null;
	fireplace:      null;
	garage:         null;
	garage_spaces:  null;
	heating:        null;
	lot_size:       number;
	pool:           null;
	prop_type:      string;
	roofing:        null;
	rooms:          null;
	sqft:           number;
	stories:        number;
	style:          null;
	units:          number;
	view:           null;
	year_built:     number;
	year_renovated: null;
	zoning:         string;
}

export interface Raw {
	status:     string;
	tax_amount: null;
}

export interface School {
	nces_id:                string;
	id:                     string;
	greatschools_id:        string;
	name:                   string;
	education_levels:       EducationLevel[];
	funding_type:           string;
	lat:                    number;
	lon:                    number;
	student_count:          number;
	student_teacher_ratio?: number;
	location:               Location;
	phone:                  string;
	distance_in_miles:      number;
	grades:                 Grades;
	relevance:              string;
	ratings:                Ratings;
}

export enum EducationLevel {
	Elementary = "elementary",
	High = "high",
	Middle = "middle",
}

export interface Grades {
	range: Range;
}

export interface Range {
	low:  string;
	high: string;
}

export interface Location {
	city_slug_id: string;
	postal_code:  string;
	state:        string;
	county:       string;
	city:         string;
	street:       string;
}

export interface Ratings {
	great_schools_rating: number | null;
	parent_rating:        number;
}

export interface SoldHistory {
	date:    string;
	source:  string;
	listing: ListingClass;
}

export interface ListingClass {
	price: number;
}

export interface TaxHistory {
	assessment: Assessment;
	tax:        number;
	year:       string;
}

export interface Assessment {
	building: number | null;
	land:     number;
	total:    number;
}
