// Generated by https://quicktype.io

export interface PropertyRent {
	property_id:          string;
	listing_id:           string;
	prop_type:            string;
	list_date:            string;
	last_update:          string;
	listing_status:       string;
	beds:                 number;
	baths:                number;
	price:                number;
	branding:             Branding;
	prop_status:          string;
	address:              Address;
	client_display_flags: ClientDisplayFlags;
	products:             string[];
	agents:               Agent[];
	lead_forms:           LeadForms;
	lot_size:             LotSize;
	building_size:        BuildingSize;
	rdc_web_url:          string;
	rdc_app_url:          string;
	community:            Community;
	data_source_name:     string;
	source:               string;
	page_no:              number;
	rank:                 number;
	list_tracking:        string;
	photo_count:          number;
	photos:               Photo[];
	year_built: 		  number;
}

export interface Address {
	city:                   string;
	country:                string;
	county:                 string;
	county_needed_for_uniq: boolean;
	lat:                    number;
	line:                   string;
	postal_code:            string;
	state_code:             string;
	state:                  string;
	time_zone:              string;
	neighborhood_name:      string;
	neighborhoods:          Neighborhood[];
	lon:                    number;
}

export interface Neighborhood {
	id:    string;
	level: string;
	name:  string;
}

export interface Agent {
	primary: boolean;
}

export interface Branding {
	state_license: null;
}

export interface BuildingSize {
	units: string;
}

export interface ClientDisplayFlags {
	presentation_status:            string;
	is_showcase:                    boolean;
	lead_form_phone_required:       boolean;
	price_change:                   number;
	has_specials:                   boolean;
	is_mls_rental:                  boolean;
	is_rental_community:            boolean;
	is_rental_unit:                 boolean;
	is_co_star:                     boolean;
	is_apartmentlist:               boolean;
	suppress_map_pin:               boolean;
	suppress_phone_call_lead_event: boolean;
	price_reduced:                  boolean;
	allows_cats:                    boolean;
	allows_dogs:                    boolean;
	allows_dogs_small:              boolean;
	allows_dogs_large:              boolean;
}

export interface Community {
	baths_max:      number;
	baths_min:      number;
	beds_max:       number;
	beds_min:       number;
	contact_number: string;
	id:             number;
	name:           string;
	price_max:      number;
	price_min:      number;
	price_hint:     string;
	source_id:      string;
	sqft_max:       number;
	sqft_min:       number;
	sqft_hint:      string;
}

export interface LeadForms {
	form:            Form;
	show_agent:      boolean;
	show_broker:     boolean;
	show_provider:   boolean;
	show_management: boolean;
}

export interface Form {
	name:         Email;
	email:        Email;
	move_in_date: MoveInDate;
	phone:        Phone;
	message:      Email;
	show:         boolean;
}

export interface Email {
	required:                boolean;
	minimum_character_count: number;
}

export interface MoveInDate {
	required:                boolean;
	default_date:            string;
	minimum_days_from_today: number;
	maximum_days_from_today: number;
}

export interface Phone {
	required:                boolean;
	minimum_character_count: number;
	maximum_character_count: number;
}

export interface LotSize {
	size:  number;
	units: string;
}

export interface Photo {
	href: string;
}
